version: '2'

networks:
  hospital:

services:
  redis1:
    image: 'redis:latest'
    container_name: redis.hosp1.coep.com
    command: redis-server --requirepass hosp1coep
    ports:
      - "6379:6379"
    networks:
      - hospital

  redis2:
    image: 'redis:latest'
    container_name: redis.hosp2.coep.com
    command: redis-server --requirepass hosp2coep
    ports:
      - "6380:6379"
    networks:
      - hospital

  redis3:
    image: 'redis:latest'
    container_name: redis.hosp3.coep.com
    command: redis-server --requirepass hosp3coep
    ports:
      - "6381:6379"
    networks:
      - hospital
